name: check-status
version: "0.0.0"

executables:
  check-status:
    source-dirs: src
    main: Main.hs
    other-modules:
      - BuildEnv
      - SystemInfo
    dependencies:
      - aeson
      - base
      - bytestring
      - case-insensitive
      - data-default
      - http-client
      - http-types
      - fast-logger
      - mtl
      - scotty
      - template-haskell
      - text
      - wai
      - wai-extra
      - warp
