name: check-status
version: "0.0.0"

executables:
  check-status:
    source-dirs: src
    main: Main.hs
    other-modules:
      - BuildEnv
      - SystemInfo
    dependencies:
      - aeson
      - base
      - bytestring
      - data-default
      - http-client
      - scotty
      - template-haskell
      - text
      - wai-extra
