version: 2

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.5

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}

      - run:
          name: Setup GHC and dependencies
          command: |
            stack setup
            stack install --dependencies-only

      - save_cache:
          paths:
            - ~/.stack
          key: v1-dependencies-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}

      - run:
          name: Build
          command: |
            stack build

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            stack image container

      - run:
          name: Push Docker image
          command: |
            docker tag check-status:latest magthe/check-status:${CIRCLE_BRANCH}
            docker tag magthe/check-status:${CIRCLE_BRANCH} magthe/check-status:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
            echo ${DOCKER_PASSWD} | docker login -u ${DOCKER_USER} --password-stdin
            docker push magthe/check-status

      - run:
          name: Deploy to ECS
          command: |
            apt-get update
            apt-get install -y python3-pip jq
            pip3 install awscli
            curl -L -o /usr/local/bin/ecs-deploy https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy
            chmod +x /usr/local/bin/ecs-deploy
            ecs-deploy -t 180 --skip-deployments-check -r us-east-2 -c magthe-cluster -n magthe-external-service -i magthe/check-status:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
